# Generated by Django 5.1.7 on 2025-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injectionsubstation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
