# Generated by Django 5.1.7 on 2025-06-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_injectionsubstation_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributiontransformer',
            unique_together=set(),
        ),
    ]
