# Generated by Django 5.1.7 on 2025-05-18 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_band_slug_businessdistrict_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.band'),
        ),
        migrations.AddField(
            model_name='feeder',
            name='voltage_level',
            field=models.CharField(choices=[('11kv', '11kV'), ('33kv', '33kV')], default='11kv', max_length=10),
            preserve_default=False,
        ),
    ]
