# Generated by Django 5.1.7 on 2025-05-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_feeder_band_feeder_voltage_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='business_district',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.businessdistrict'),
            preserve_default=False,
        ),
    ]
