# Generated by Django 5.1.7 on 2025-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_feeder_business_district'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='injectionsubstation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='injectionsubstation',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='injectionsubstation',
            name='district',
        ),
    ]
