# Generated by Django 5.1.7 on 2025-05-28 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_injectionsubstation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='business_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='common.businessdistrict'),
        ),
    ]
