# Generated by Django 5.1.7 on 2025-04-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_band_slug_businessdistrict_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collection_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=10)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
                ('transformer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.distributiontransformer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRevenueBilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_monthly_revenue_billed', to='common.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('assigned_transformers', models.ManyToManyField(to='common.distributiontransformer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('outstanding_billed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_billed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collections', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_run_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collections_on_outstanding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active_accounts', models.PositiveIntegerField()),
                ('suspended_accounts', models.PositiveIntegerField()),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.salesrepresentative')),
            ],
        ),
    ]
