# Generated by Django 5.1.7 on 2025-07-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Opex',
        ),
        migrations.RenameModel(
            old_name='ExpenseCategory',
            new_name='OpexCategory',
        ),
    ]
