# Generated by Django 5.1.7 on 2025-07-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('financial', '0002_rename_expense_opex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opex',
            options={'ordering': ['-date'], 'verbose_name': 'OPEX', 'verbose_name_plural': 'OPEX Records'},
        ),
        migrations.AlterField(
            model_name='opex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the record was created'),
        ),
        migrations.AlterField(
            model_name='opex',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual expense amount (credit side)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='opex',
            name='date',
            field=models.DateField(help_text='Date of the expense'),
        ),
        migrations.AlterField(
            model_name='opex',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount sent from HQ (debit side)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='opex',
            name='district',
            field=models.ForeignKey(help_text='Which business district this OPEX belongs to', on_delete=django.db.models.deletion.CASCADE, to='common.businessdistrict'),
        ),
        migrations.AlterField(
            model_name='opex',
            name='gl_account_number',
            field=models.CharField(help_text='General ledger account number', max_length=20),
        ),
        migrations.AlterField(
            model_name='opex',
            name='gl_breakdown',
            field=models.ForeignKey(help_text='GL breakdown mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.glbreakdown'),
        ),
        migrations.AlterField(
            model_name='opex',
            name='opex_category',
            field=models.ForeignKey(help_text='Categorization of the OPEX (e.g. admin, technical, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.opexcategory'),
        ),
        migrations.AlterField(
            model_name='opex',
            name='payee',
            field=models.CharField(help_text='Who was paid', max_length=200),
        ),
        migrations.AlterField(
            model_name='opex',
            name='purpose',
            field=models.TextField(help_text='What the expenditure was for'),
        ),
    ]
