# Generated by Django 5.1.7 on 2025-05-18 20:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_feeder_band_feeder_voltage_level'),
        ('financial', '0002_alter_dailycollection_id_alter_expense_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='month',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='purpose',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='feeder',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='transformer',
        ),
        migrations.AddField(
            model_name='expense',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='debit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='expense',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.businessdistrict'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='gl_account_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='opex_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payee',
            field=models.CharField(default='67e7ed2e-51a0-8013-99a0-f496ca40dff0', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='gl_breakdown',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.glbreakdown'),
        ),
    ]
