# Generated by Django 5.1.7 on 2025-05-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_injectionsubstation_unique_together_and_more'),
        ('financial', '0003_glbreakdown_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='assigned_transformers',
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='assigned_feeders',
            field=models.ManyToManyField(to='common.feeder'),
        ),
    ]
