# Generated by Django 5.1.7 on 2025-07-15 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('financial', '0003_alter_opex_options_alter_opex_created_at_and_more'),
        ('hr', '0004_alter_department_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Invoice month (e.g. 2025-07-01)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='MO invoice amount', max_digits=15)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this invoice has been paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='NBETInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Invoice month (e.g. 2025-07-01)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='NBET invoice amount', max_digits=15)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether this invoice has been paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='MYTOTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('effective_date', models.DateField(help_text='Date this tariff rate took effect')),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, help_text='Allowed tariff (₦/kWh)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('band', models.ForeignKey(help_text='Service band (A–E)', on_delete=django.db.models.deletion.CASCADE, to='common.band')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('band', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='Year-month this salary run is for (e.g. 2025-07-01)')),
                ('payment_date', models.DateField(help_text='Date salary was actually paid')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Salary amount paid', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('district', models.ForeignKey(help_text='Which business district this salary payment covers', on_delete=django.db.models.deletion.CASCADE, to='common.businessdistrict')),
                ('staff', models.ForeignKey(help_text='Staff member who received this salary payment', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.staff')),
            ],
            options={
                'ordering': ['-month', 'staff__full_name'],
                'unique_together': {('district', 'month', 'staff')},
            },
        ),
    ]
