# Generated by Django 5.1.7 on 2025-05-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_remove_salesrepresentative_assigned_transformers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='assigned_feeders',
        ),
        migrations.DeleteModel(
            name='SalesRepPerformance',
        ),
        migrations.DeleteModel(
            name='SalesRepresentative',
        ),
    ]
