# Generated by Django 5.1.7 on 2025-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_mytotariff_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='opex',
            name='transaction_id',
            field=models.PositiveIntegerField(default=1, help_text='Transaction ID'),
            preserve_default=False,
        ),
    ]
