# Generated by Django 5.1.7 on 2025-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_mytotariff_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='opex',
            name='external_id',
            field=models.CharField(blank=True, help_text='External identifier from DataNest', max_length=100, null=True, unique=True),
        ),
    ]
