# Generated by Django 5.1.7 on 2025-05-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_salesrepresentative_assigned_feeders_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCollection',
        ),
    ]
