# Generated by Django 5.1.7 on 2025-07-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_opex_external_id'),
        ('financial', '0008_alter_opex_transaction_id'),
    ]

    operations = [
    ]
