# Generated by Django 5.1.7 on 2025-07-25 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_merge_20250725_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='HQOpex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, help_text='External identifier from DataNest', max_length=100, null=True, unique=True)),
                ('date', models.DateField(help_text='Date of the HQ expense')),
                ('purpose', models.TextField(help_text='What the expenditure was for')),
                ('payee', models.CharField(help_text='Who was paid', max_length=200)),
                ('gl_account_number', models.CharField(help_text='General ledger account number', max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount sent out from HQ (debit)', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual expense amount (credit)', max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('gl_breakdown', models.ForeignKey(help_text='GL breakdown mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.glbreakdown')),
                ('opex_category', models.ForeignKey(help_text='Categorization of the HQ OPEX (e.g. admin, ICT, audit)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.opexcategory')),
            ],
            options={
                'verbose_name': 'HQ OPEX',
                'verbose_name_plural': 'HQ OPEX Records',
                'ordering': ['-date'],
            },
        ),
    ]
