# Generated by Django 5.1.7 on 2025-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(blank=True, choices=[('associate', 'Associate'), ('graduate_trainee', 'Graduate Trainee'), ('management_trainee', 'Management Trainee'), ('junior_assistant', 'Junior Assistant'), ('senior_manager', 'Senior Manager')], max_length=100, null=True),
        ),
    ]
