# Generated by Django 5.1.7 on 2025-05-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_staff_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='grade',
            field=models.CharField(blank=True, choices=[('associate', 'Associate'), ('graduate_trainee', 'Graduate Trainee'), ('management_trainee', 'Management Trainee'), ('junior_assistant', 'Junior Assistant'), ('senior_manager', 'Senior Manager')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
