# Generated by Django 5.1.7 on 2025-06-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_staff_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
