# Generated by Django 5.1.7 on 2025-04-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_band_slug_businessdistrict_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interruption_type', models.CharField(choices=[('load_shedding', 'Load Shedding'), ('fault', 'Fault'), ('permit', 'Permit')], max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField()),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='DailyHoursOfSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_supplied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EnergyDelivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HourlyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('load_mw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date', 'hour')},
            },
        ),
    ]
