# Generated by Django 5.1.7 on 2025-06-16 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHoursOfSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours_supplied', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EnergyDelivered',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('energy_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FeederInterruption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('interruption_type', models.CharField(choices=[('E/F', 'Earth Fault'), ('O/C', 'Overcurrent'), ('O/C & E/F', 'Overcurrent and Earth Fault'), ('NO RI', 'No RI'), ('N/A', 'Not Specified')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'occurred_at', 'interruption_type')},
            },
        ),
        migrations.CreateModel(
            name='HourlyLoad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField()),
                ('load_mw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date', 'hour')},
            },
        ),
    ]
