# Generated by Django 5.1.7 on 2025-05-18 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhoursofsupply',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='energydelivered',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feederinterruption',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hourlyload',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
