# Generated by Django 5.1.7 on 2025-07-15 15:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
        ('technical', '0002_alter_feederinterruption_interruption_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederEnergyDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the delivery')),
                ('energy_mwh', models.DecimalField(decimal_places=4, help_text='Total energy delivered (MWh) on that date', max_digits=14)),
                ('feeder', models.ForeignKey(help_text='Which feeder this daily total applies to', on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'ordering': ['-date', 'feeder'],
                'indexes': [models.Index(fields=['date', 'feeder'], name='technical_f_date_97735d_idx')],
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FeederEnergyMonthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('period', models.DateField(db_index=True, help_text='First day of the period month, e.g. 2025-07-01')),
                ('energy_mwh', models.DecimalField(decimal_places=4, help_text='Total energy delivered (MWh) in that month', max_digits=16)),
                ('feeder', models.ForeignKey(help_text='Which feeder this monthly total applies to', on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'ordering': ['-period', 'feeder'],
                'indexes': [models.Index(fields=['period', 'feeder'], name='technical_f_period_3c5445_idx')],
                'unique_together': {('feeder', 'period')},
            },
        ),
    ]
