# Generated by Django 5.1.7 on 2025-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_injectionsubstation_unique_together_and_more'),
        ('technical', '0002_alter_dailyhoursofsupply_id_alter_energydelivered_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feederinterruption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feederinterruption',
            name='interruption_type',
            field=models.CharField(choices=[('E/F', 'Earth Fault'), ('O/C', 'Overcurrent'), ('O/C & E/F', 'Overcurrent and Earth Fault'), ('NO RI', 'No RI'), ('Earth Fault', 'Earth Fault'), ('Overcurrent & Earth Fault', 'Overcurrent and Earth Fault'), ('Overcurrent Fault', 'Overcurrent Fault'), ('N/A', 'Not Specified')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='feederinterruption',
            unique_together={('feeder', 'occurred_at', 'interruption_type')},
        ),
    ]
