# Generated by Django 5.1.7 on 2025-05-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_feederinterruption_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederinterruption',
            name='interruption_type',
            field=models.CharField(choices=[('E/F', 'Earth Fault'), ('O/C', 'Overcurrent'), ('O/C & E/F', 'Overcurrent and Earth Fault'), ('NO RI', 'No RI'), ('N/A', 'Not Specified')], max_length=50),
        ),
    ]
