# Generated by Django 5.1.7 on 2025-05-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0004_alter_feederinterruption_interruption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederinterruption',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
