# Generated by Django 5.1.7 on 2025-05-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_band_slug_businessdistrict_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAPIStreamingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_metered', models.IntegerField()),
                ('total_unmetered', models.IntegerField()),
                ('streaming_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nerc_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyEstimatedBillingCapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('estimated_billing_efficiency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('customers_billed_within_cap', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_energy_overbilled', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nerc_target_efficiency', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyForumDecisionCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('decisions_issued', models.IntegerField()),
                ('decisions_implemented', models.IntegerField()),
                ('compliance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nerc_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyNERCComplaintResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('complaints_received', models.IntegerField()),
                ('complaints_resolved', models.IntegerField()),
                ('resolved_within_sla', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nerc_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyUSoASubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('timeliness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('completeness', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nerc_target_timeliness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nerc_target_completeness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nerc_target_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyEnergyOfftake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('available_nomination_mwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('energy_offtake_mwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('offtake_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nerc_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRevenueRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('allowed_tariff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue_recovered', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recovery_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nerc_target', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
        ),
    ]
