# Generated by Django 5.1.7 on 2025-07-25 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid'), ('Unmetered', 'Unmetered')], max_length=20)),
                ('metering_type', models.CharField(choices=[('MD1', 'MD1'), ('MD2', 'MD2'), ('Non-MD', 'Non-MD')], max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.band')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.distributiontransformer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('assigned_transformers', models.ManyToManyField(to='common.distributiontransformer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesRepPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('outstanding_billed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_billed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collections', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_run_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collections_on_outstanding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active_accounts', models.PositiveIntegerField()),
                ('suspended_accounts', models.PositiveIntegerField()),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyEnergyDelivered',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('energy_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCustomerStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('customer_count', models.PositiveIntegerField()),
                ('customers_billed', models.PositiveIntegerField()),
                ('customer_response_count', models.PositiveIntegerField()),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyEnergyBilled',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('energy_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyRevenueBilled',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.distributiontransformer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative')),
            ],
            options={
                'ordering': ['-month', 'sales_rep', 'transformer'],
                'unique_together': {('sales_rep', 'transformer', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCommercialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('customers_billed', models.PositiveIntegerField(default=0)),
                ('customers_responded', models.PositiveIntegerField(default=0)),
                ('revenue_billed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revenue_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.distributiontransformer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative')),
            ],
            options={
                'unique_together': {('sales_rep', 'transformer', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collection_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=10)),
                ('vendor_name', models.CharField(choices=[('BuyPower.ng', 'BuyPower.ng'), ('Banahim.net', 'Banahim.net'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('POS', 'POS'), ('powershop.ng', 'powershop.ng'), ('Remita', 'Remita')], help_text='Vendor through which collection was made', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.distributiontransformer')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative')),
            ],
            options={
                'ordering': ['-date', 'sales_rep', 'transformer'],
                'unique_together': {('sales_rep', 'transformer', 'date', 'collection_type', 'vendor_name')},
            },
        ),
    ]
