# Generated by Django 5.1.7 on 2025-04-01 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_band_slug_businessdistrict_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid'), ('Unmetered', 'Unmetered')], max_length=20)),
                ('metering_type', models.CharField(choices=[('MD1', 'MD1'), ('MD2', 'MD2'), ('Non-MD', 'Non-MD')], max_length=20)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('band', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.band')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.distributiontransformer')),
            ],
        ),
        migrations.CreateModel(
            name='DailyEnergyDelivered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyRevenueCollected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCustomerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('customer_count', models.PositiveIntegerField()),
                ('customers_billed', models.PositiveIntegerField()),
                ('customer_response_count', models.PositiveIntegerField()),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyEnergyBilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('energy_mwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyRevenueBilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'unique_together': {('feeder', 'month')},
            },
        ),
    ]
