# Generated by Django 5.1.7 on 2025-04-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('common', '0003_band_slug_businessdistrict_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrevenuebilled',
            name='feeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_monthly_revenue_billed', to='common.feeder'),
        ),
    ]
