# Generated by Django 5.1.7 on 2025-06-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='assigned_feeders',
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='assigned_transformers',
            field=models.ManyToManyField(to='common.distributiontransformer'),
        ),
    ]
