# Generated by Django 5.1.7 on 2025-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycollection',
            name='customers_collected',
            field=models.PositiveIntegerField(default=0, help_text='Number of customers who made payments/collections on this date'),
        ),
        migrations.AddField(
            model_name='monthlyrevenuebilled',
            name='customers_billed',
            field=models.PositiveIntegerField(default=0, help_text='Number of customers billed in this month'),
        ),
    ]
