# Generated by Django 5.1.7 on 2025-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_remove_salesrepresentative_assigned_feeders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycollection',
            name='vendor_name',
            field=models.CharField(choices=[('BuyPower.ng', 'BuyPower.ng'), ('Banahim.net', 'Banahim.net'), ('Bank', 'Bank'), ('Cash', 'Cash'), ('POS', 'POS'), ('powershop.ng', 'powershop.ng'), ('Remita', 'Remita')], default='Cash', help_text='Vendor through which collection was made', max_length=20),
            preserve_default=False,
        ),
    ]
