# Generated by Django 5.1.7 on 2025-07-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_alter_dailycollection_vendor_name'),
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlycommercialsummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlycommercialsummary',
            name='transformer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.distributiontransformer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='monthlycommercialsummary',
            unique_together={('sales_rep', 'transformer', 'month')},
        ),
    ]
