# Generated by Django 5.1.7 on 2025-05-26 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0003_alter_customer_id_alter_dailyenergydelivered_id_and_more'),
        ('common', '0006_alter_injectionsubstation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('assigned_feeders', models.ManyToManyField(to='common.feeder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesRepPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('outstanding_billed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_billed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collections', models.DecimalField(decimal_places=2, max_digits=15)),
                ('daily_run_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collections_on_outstanding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active_accounts', models.PositiveIntegerField()),
                ('suspended_accounts', models.PositiveIntegerField()),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
