# Generated by Django 5.1.7 on 2025-07-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_dailycollection_customers_collected_and_more'),
        ('commercial', '0004_recreate_monthlyrevenuebilled'),
    ]

    operations = [
    ]
