# Generated by Django 5.1.7 on 2025-07-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_alter_monthlycommercialsummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlycommercialsummary',
            unique_together={('sales_rep', 'month')},
        ),
        migrations.DeleteModel(
            name='DailyRevenueCollected',
        ),
        migrations.RemoveField(
            model_name='monthlycommercialsummary',
            name='transformer',
        ),
    ]
