# Generated by Django 5.1.7 on 2025-05-26 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_salesrepresentative_salesrepperformance'),
        ('common', '0006_alter_injectionsubstation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('collection_type', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], max_length=10)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feeder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
