# Generated by Django 5.1.7 on 2025-07-27 16:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_merge_20250727_1619'),
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyrevenuebilled',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='monthlyrevenuebilled',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from collection tool', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monthlyrevenuebilled',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from collection tool', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesrepperformance',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from collection tool', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesrepperformance',
            name='transformer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.distributiontransformer'),
        ),
        migrations.AlterField(
            model_name='monthlyrevenuebilled',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
