# Generated by Django 5.1.7 on 2025-05-26 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0005_dailycollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycollection',
            name='feeder',
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='sales_rep',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative'),
            preserve_default=False,
        ),
    ]
