# Generated by Django 5.1.7 on 2025-07-24 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_alter_monthlycommercialsummary_unique_together_and_more'),
        ('common', '0003_alter_distributiontransformer_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailycollection',
            options={'ordering': ['-date', 'sales_rep', 'transformer']},
        ),
        migrations.AddField(
            model_name='dailycollection',
            name='transformer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='common.distributiontransformer'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailycollection',
            unique_together={('sales_rep', 'transformer', 'date', 'collection_type', 'vendor_name')},
        ),
    ]
