# Generated by Django 5.1.7 on 2025-05-26 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0006_remove_dailycollection_feeder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCommercialSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('customers_billed', models.PositiveIntegerField(default=0)),
                ('customers_responded', models.PositiveIntegerField(default=0)),
                ('revenue_billed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('revenue_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commercial.salesrepresentative')),
            ],
            options={
                'unique_together': {('sales_rep', 'month')},
            },
        ),
    ]
